# Site
name: "Omnius Project"
title: "Omnius Project"
description: "Markdown Editor"
meta_description: "Markdown Editor"
logo: ''
favicon: ''
paginate: 12
baseurl: '/'
email: 'woojiahao1234@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  woojiahao:
    name: Woo Jia Hao
    display_name: Woo Jia Hao
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: woojiahao1234@gmail.com
    description: "Creator and manager of the Omnius project."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge